test 1

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -458,56 +458,56 @@ steps:
 #     echo "✅ Hermes 파일 교체 완료!"
 #   displayName: '[중요] IPA 내 Hermes 파일 교체 및 검증'
 
-# - script: |
-#     # Grant execution permission to generate_hash script
-#     HASH_SCRIPT_PATH="$(Build.SourcesDirectory)/ios/AppSealingSDK/generate_hash"
-#     # echo "-------------------------------------"
-#     # cd "$(Build.SourcesDirectory)/ios/AppSealingSDK"
-#     # ls -al
-#     # echo "-------------------------------------"
-#     EXPORT_DIR="$(Build.ArtifactStagingDirectory)"
-#     # cd "$EXPORT_DIR"
-#     # ls -al
-#     # echo "-------------------------------------"
-#     IPA_PATH=$(find "$EXPORT_DIR" -type f -name "*.ipa" | head -n 1)
+- script: |
+    # Grant execution permission to generate_hash script
+    HASH_SCRIPT_PATH="$(Build.SourcesDirectory)/ios/AppSealingSDK/generate_hash"
+    # echo "-------------------------------------"
+    # cd "$(Build.SourcesDirectory)/ios/AppSealingSDK"
+    # ls -al
+    # echo "-------------------------------------"
+    EXPORT_DIR="$(Build.ArtifactStagingDirectory)"
+    # cd "$EXPORT_DIR"
+    # ls -al
+    # echo "-------------------------------------"
+    IPA_PATH=$(find "$EXPORT_DIR" -type f -name "*.ipa" | head -n 1)
 
-#     echo "Granting execution permission to generate_hash..."
-#     chmod +x "$HASH_SCRIPT_PATH"
+    echo "Granting execution permission to generate_hash..."
+    chmod +x "$HASH_SCRIPT_PATH"
 
-#     echo "Running generate_hash with IPA... $IPA_PATH"
-#     "$HASH_SCRIPT_PATH" "$IPA_PATH"
-#   displayName: 'Run generate_hash on IPA'
+    echo "Running generate_hash with IPA... $IPA_PATH"
+    "$HASH_SCRIPT_PATH" "$IPA_PATH"
+  displayName: 'Run generate_hash on IPA'
 
-# - script: |
-#     # Upload the IPA file to TestFlight using altool
-#     IPA_PATH=$(find "$(Build.ArtifactStagingDirectory)" -type f -name "*.ipa" | head -n 1)
+- script: |
+    # Upload the IPA file to TestFlight using altool
+    IPA_PATH=$(find "$(Build.ArtifactStagingDirectory)" -type f -name "*.ipa" | head -n 1)
 
-#     if [ -f "$IPA_PATH" ]; then
-#         xcrun altool --upload-app \
-#           -f "$IPA_PATH" \
-#           -t ios \
-#           -u "${{ parameters.APPLE_ID }}" \
-#           -p "${{ parameters.APP_SPECIFIC_PASSWORD }}"
+    if [ -f "$IPA_PATH" ]; then
+        xcrun altool --upload-app \
+          -f "$IPA_PATH" \
+          -t ios \
+          -u "${{ parameters.APPLE_ID }}" \
+          -p "${{ parameters.APP_SPECIFIC_PASSWORD }}"
 
-#         echo "Uploaded IPA to TestFlight successfully."
-#     else
-#         echo "IPA file not found. Skipping upload."
-#         exit 1
-#     fi
-#   displayName: 'Upload to TestFlight'
+        echo "Uploaded IPA to TestFlight successfully."
+    else
+        echo "IPA file not found. Skipping upload."
+        exit 1
+    fi
+  displayName: 'Upload to TestFlight'
 
-# - script: |
-#     # Cleanup temporary keychain and build artifacts
-#     TEMP_KEYCHAIN_PATH="$HOME/Library/Keychains/temp-keychain.keychain-db"
+- script: |
+    # Cleanup temporary keychain and build artifacts
+    TEMP_KEYCHAIN_PATH="$HOME/Library/Keychains/temp-keychain.keychain-db"
 
-#     if [ -f "$TEMP_KEYCHAIN_PATH" ]; then
-#         security delete-keychain "$TEMP_KEYCHAIN_PATH"
-#         echo "Temporary keychain deleted successfully."
-#     else
-#         echo "Temporary keychain not found. Skipping deletion."
-#     fi
+    if [ -f "$TEMP_KEYCHAIN_PATH" ]; then
+        security delete-keychain "$TEMP_KEYCHAIN_PATH"
+        echo "Temporary keychain deleted successfully."
+    else
+        echo "Temporary keychain not found. Skipping deletion."
+    fi
 
-#     rm -rf "$(Build.ArtifactStagingDirectory)" ios/build ios/Pods ios/Podfile.lock
+    rm -rf "$(Build.ArtifactStagingDirectory)" ios/build ios/Pods ios/Podfile.lock
 
-#     echo "Cleanup completed."
-#   displayName: 'Cleanup Temporary Files'
+    echo "Cleanup completed."
+  displayName: 'Cleanup Temporary Files'
